// PAULO SENSI — Base de dados offline (sem servidor)
window.PS_DB = {
  brands: [
    {
      id: "samsung",
      name: "Samsung",
      models: [
        "Galaxy A05",
        "Galaxy A05s",
        "Galaxy A06",
        "Galaxy A10",
        "Galaxy A10s",
        "Galaxy A11",
        "Galaxy A12",
        "Galaxy A13 4G",
        "Galaxy A13 5G",
        "Galaxy A14 4G",
        "Galaxy A14 5G",
        "Galaxy A15 4G",
        "Galaxy A15 5G",
        "Galaxy A16 4G",
        "Galaxy A16 5G",
        "Galaxy A20",
        "Galaxy A20s",
        "Galaxy A21s",
        "Galaxy A22 4G",
        "Galaxy A22 5G",
        "Galaxy A23 4G",
        "Galaxy A23 5G",
        "Galaxy A24",
        "Galaxy A25 5G",
        "Galaxy A30",
        "Galaxy A30s",
        "Galaxy A31",
        "Galaxy A32 4G",
        "Galaxy A32 5G",
        "Galaxy A33 5G",
        "Galaxy A34 5G",
        "Galaxy A35 5G",
        "Galaxy A50",
        "Galaxy A50s",
        "Galaxy A51",
        "Galaxy A52",
        "Galaxy A52s 5G",
        "Galaxy A53 5G",
        "Galaxy A54 5G",
        "Galaxy A55 5G",
        "Galaxy M10",
        "Galaxy M11",
        "Galaxy M12",
        "Galaxy M13",
        "Galaxy M14 5G",
        "Galaxy M15 5G",
        "Galaxy M20",
        "Galaxy M21",
        "Galaxy M22",
        "Galaxy M23 5G",
        "Galaxy M30",
        "Galaxy M31",
        "Galaxy M32",
        "Galaxy M33 5G",
        "Galaxy M34 5G",
        "Galaxy M35 5G",
        "Galaxy S8",
        "Galaxy S9",
        "Galaxy S10e",
        "Galaxy S10",
        "Galaxy S10+",
        "Galaxy S20 FE",
        "Galaxy S21",
        "Galaxy S21 FE",
        "Galaxy S22",
        "Galaxy S22 Ultra",
        "Galaxy S23",
        "Galaxy S23 Ultra",
        "Galaxy S24",
        "Galaxy S24 Ultra"
      ]
    },
    {
      id: "xiaomi",
      name: "Xiaomi / Redmi / POCO",
      models: [
        "Redmi 9A",
        "Redmi 9C",
        "Redmi 10",
        "Redmi 10C",
        "Redmi 12",
        "Redmi 12C",
        "Redmi 13C",
        "Redmi Note 8",
        "Redmi Note 9",
        "Redmi Note 10",
        "Redmi Note 10S",
        "Redmi Note 11",
        "Redmi Note 11S",
        "Redmi Note 12",
        "Redmi Note 12 Pro",
        "Redmi Note 13",
        "Redmi Note 13 Pro",
        "POCO M3",
        "POCO M4 Pro",
        "POCO M5",
        "POCO M6",
        "POCO X3 NFC",
        "POCO X3 Pro",
        "POCO X4 Pro",
        "POCO X5",
        "POCO X5 Pro",
        "POCO F3",
        "POCO F4",
        "POCO F5",
        "Xiaomi 11 Lite",
        "Xiaomi 12",
        "Xiaomi 12 Lite",
        "Xiaomi 13",
        "Xiaomi 13 Lite"
      ]
    },
    {
      id: "motorola",
      name: "Motorola",
      models: [
        "Moto E6 Plus",
        "Moto E7",
        "Moto E7 Plus",
        "Moto E13",
        "Moto E20",
        "Moto E22",
        "Moto E32",
        "Moto E40",
        "Moto G20",
        "Moto G22",
        "Moto G23",
        "Moto G30",
        "Moto G31",
        "Moto G32",
        "Moto G34 5G",
        "Moto G41",
        "Moto G42",
        "Moto G50 5G",
        "Moto G52",
        "Moto G53 5G",
        "Moto G54 5G",
        "Moto G60",
        "Moto G62 5G",
        "Moto G71 5G",
        "Moto G72",
        "Moto G73 5G",
        "Moto G84 5G",
        "Moto Edge 20",
        "Moto Edge 30",
        "Moto Edge 40",
        "Moto Edge 50",
        "Moto Edge 50 Fusion"
      ]
    },
    {
      id: "apple",
      name: "Apple (iPhone)",
      models: [
        "iPhone 7",
        "iPhone 8",
        "iPhone X",
        "iPhone XR",
        "iPhone XS",
        "iPhone 11",
        "iPhone 11 Pro",
        "iPhone 12",
        "iPhone 12 Pro",
        "iPhone 13",
        "iPhone 13 Pro",
        "iPhone 14",
        "iPhone 14 Pro",
        "iPhone 15",
        "iPhone 15 Pro"
      ]
    },
    {
      id: "realme",
      name: "realme",
      models: [
        "realme C11",
        "realme C21",
        "realme C25",
        "realme C33",
        "realme C35",
        "realme C53",
        "realme C55",
        "realme 8",
        "realme 9",
        "realme 10",
        "realme 11",
        "realme GT Neo 2",
        "realme GT 2"
      ]
    },
    {
      id: "asus",
      name: "ASUS",
      models: [
        "ROG Phone 3",
        "ROG Phone 5",
        "ROG Phone 6",
        "ROG Phone 7",
        "Zenfone 8",
        "Zenfone 9",
        "Zenfone 10"
      ]
    },
    {
      id: "oppo",
      name: "OPPO",
      models: [
        "OPPO A15",
        "OPPO A16",
        "OPPO A17",
        "OPPO A54",
        "OPPO A57",
        "OPPO Reno 6",
        "OPPO Reno 7",
        "OPPO Reno 8"
      ]
    },
    {
      id: "vivo",
      name: "vivo",
      models: [
        "vivo Y15",
        "vivo Y20",
        "vivo Y21",
        "vivo Y22",
        "vivo V21",
        "vivo V23",
        "vivo V25"
      ]
    }
  ],

  // Valores base por tier (o app gera variação leve por marca/modelo)
  defaultSensiByTier: {
    free: {
      geral: 165,
      redDot: 160,
      x2: 150,
      x4: 140,
      awm: 120,
      olhadinha: 150,
      dpi: 520,
      botao: 48
    },
    standard: {
      geral: 175,
      redDot: 170,
      x2: 160,
      x4: 150,
      awm: 130,
      olhadinha: 160,
      dpi: 560,
      botao: 50
    },
    premium: {
      geral: 185,
      redDot: 178,
      x2: 168,
      x4: 158,
      awm: 138,
      olhadinha: 168,
      dpi: 600,
      botao: 52
    }
  },

  // Pequenos ajustes por marca (pra diferenciar)
  brandTweaks: {
    samsung: { geral: 2, redDot: 2, x2: 1, x4: 1, awm: 0, olhadinha: 1, dpi: 10, botao: 0 },
    xiaomi:  { geral: 1, redDot: 1, x2: 2, x4: 2, awm: 1, olhadinha: 1, dpi: 20, botao: 1 },
    motorola:{ geral: 0, redDot: 1, x2: 1, x4: 1, awm: 1, olhadinha: 0, dpi: 15, botao: 0 },
    apple:   { geral: 3, redDot: 3, x2: 2, x4: 2, awm: 2, olhadinha: 2, dpi: 0,  botao: -2 },
    realme:  { geral: 1, redDot: 2, x2: 2, x4: 1, awm: 1, olhadinha: 1, dpi: 18, botao: 1 },
    asus:    { geral: 2, redDot: 2, x2: 2, x4: 2, awm: 2, olhadinha: 2, dpi: 25, botao: 2 },
    oppo:    { geral: 1, redDot: 1, x2: 1, x4: 1, awm: 1, olhadinha: 1, dpi: 12, botao: 0 },
    vivo:    { geral: 1, redDot: 1, x2: 1, x4: 1, awm: 0, olhadinha: 1, dpi: 12, botao: 0 }
  }
};